#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# copy flange surface from resources directory

touch test-zoneDistribute.foam
runApplication blockMesh
#runApplication surfaceFeatureExtract
runApplication snappyHexMesh -overwrite
runApplication decomposePar
runParallel test-zoneDistribute

#------------------------------------------------------------------------------
