#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

for t in $(foamListTimes)
do
    U=$(awk '/1\(\(/{print $2}' "$t/lagrangian/kinematicCloud/U")
    echo "$t $U"
done

#------------------------------------------------------------------------------
