#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

vibroAcousticCase=../fullCase
dataDir=postProcessing/surfaces/window

runApplication extrudeMesh
runApplication changeDictionary -constant 
runApplication topoSet
runApplication createPatch -overwrite
runApplication decomposePar
runParallel $(getApplication)

mkdir $vibroAcousticCase/constant/boundaryData/window
cp -r $dataDir/* $vibroAcousticCase/constant/boundaryData/window

# -----------------------------------------------------------------------------
