#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial run functions
#------------------------------------------------------------------------------

cleanCase0
rm -rf system/blockMeshDict
rm -rf VTK
