#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
runApplication topoSet
rm log.topoSet
runApplication topoSet -dict system/topoSetDict.f1
# Restore initial fields
restore0Dir

runApplication splitMeshRegions -cellZones -overwrite

# Remove fluid fields from solid regions (important for post-processing)
fields="nut alphat epsilon k U p_rgh"

for region in $(foamListRegions solid)
do
    remove0DirFields -region "$region" -- $fields
done

for region in $(foamListRegions)
do
    runApplication -s $region changeDictionary -region $region
done

runApplication createBaffles -region rightFluid -overwrite

echo
echo "End"

#------------------------------------------------------------------------------
