#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory
#------------------------------------------------------------------------------

# echo "cleaning ${PWD##*/}"
wclean libso saturationModels

wclean libso multiphaseSystem
wclean libso functionObjects

wclean libso twoPhaseSystem
wclean libso twoPhaseCompressibleTurbulenceModels

#------------------------------------------------------------------------------
