#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf constant/boundaryData/*
rm -f constant/faMesh/faceLabels > /dev/null 2>&1
rm -f constant/faMesh/faBoundary > /dev/null 2>&1

