#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

#runApplication blockMesh
#runApplication snappyHexMesh -overwrite
#runApplication makeFaMesh
runApplication decomposePar -force
runParallel acousticFoam  
runApplication reconstructPar
