#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

rm -rf constant/geometry
rm -rf constant/extendedFeatureEdgeMesh
rm -rf constant/geometry

#- From pointMesh generation
rm -rf constant/pointMesh
rm -rf constant/triSurface

#------------------------------------------------------------------------------
