#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication dsmcInitialise

runParallel -s decompose redistributePar -decompose -overwrite -withZero

runParallel $(getApplication)

runParallel -s reconstruct redistributePar -reconstruct

#------------------------------------------------------------------------------
