#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

(cd case_init && ./Allclean)
(cd fullCase && ./Allclean)

# -----------------------------------------------------------------------------
