#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Run a precursor init case
# main case
(cd fullCase && ./Allrun.pre)
(cd case_init && ./Allrun)

# Run the main case
(cd fullCase && ./Allrun)

# -----------------------------------------------------------------------------
