#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

runParallel -s decompose redistributePar -decompose -no-finite-area

runParallel makeFaMesh -all-area-regions

runParallel $(getApplication)

# runParallel -s reconstruct redistributePar -reconstruct

#------------------------------------------------------------------------------
