#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

runApplication makeFaMesh -all-area-regions

runApplication decomposePar -all-area-regions

runParallel $(getApplication)

runApplication reconstructPar -all-area-regions

#------------------------------------------------------------------------------
