#!/bin/sh
cd "${0%/*}" || exit            # Run from this directory
set -- -no-recursion "$@"       # Parse arguments only
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments
. ${WM_PROJECT_DIR:?}/wmake/scripts/wmakeFunctions  # Require wmake functions

#------------------------------------------------------------------------------
# Environment
#   - FOAM_MPI_LIBBIN (optional: defaults to FOAM_LIBBIN/FOAM_MPI)

# Never need/want openmp for MPI interfaces
wmakeLibMpi -no-openmp mpi

#------------------------------------------------------------------------------
