#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

(cd inlet && cleanCase)
(cd top && cleanCase)
(cd bottom && cleanCase)

cleanCase

#------------------------------------------------------------------------------
