#!/bin/sh
cd "${0%/*}" || exit                        # Run from this directory
#------------------------------------------------------------------------------

# settings

    # operand setups
    setups="
    kR-0.1
    kR-1.0
    kR-5.0
    "


#------------------------------------------------------------------------------

plot_z_vs_q() {

    setup="$1"

    endTime=$(foamDictionary results/"$setup"/system/controlDict -entry endTime -value)
    benchmarkFile="resources/dataset/Fig4-$setup.dat"
    sampleFile="results/$setup/postProcessing/sets1/$endTime/z_qr.xy"
    image="plots/z_vs_q_$setup.png"

    gnuplot<<PLT_Z_VS_Q
    set terminal pngcairo font "helvetica,20" size 1000, 1000
    set grid
    if ( "$setup" eq 'kR-5.0' ) set key bottom right; else set key top right
    set xrange [0:1]
    set yrange [0:1]
    set key samplen 2
    set key spacing 0.75
    set xlabel "z/z_c"
    set ylabel "q_w/({/Symbol s} T_{ref}^4)"
    set offset .05, .05
    set output "$image"
    set title "Nondimensional radial heat flux"

    # Benchmark
        benchmark = "$benchmarkFile"

    # OpenFOAM
        samples="$sampleFile"
        zc=2.0
        Tref=1000.0
        sigma=5.6704e-8

    plot \
        benchmark u 1:2 t "Analytical (Dua and Cheng, 1975)" w p ps 1.5 pt 7 lc rgb "black", \
        samples every 2 u (\$1/zc):(\$2/sigma/Tref**4) t "OpenFOAM" w l lw 2 lc rgb "blue"

PLT_Z_VS_Q
}


#------------------------------------------------------------------------------

# Require gnuplot
command -v gnuplot >/dev/null || {
    echo "gnuplot not found - skipping graph creation" 1>&2
    exit 1
}

# Check directory: "results"
[ -d "results" ] || {
    echo "No results directory found - skipping graph creation" 1>&2
    exit 1
}


#------------------------------------------------------------------------------

for setup in $setups
do
    echo ""
    echo "# Plots for the setup: $setup"
    echo ""

    [ -d "results/$setup" ] || {
        echo "No results/$setup directory found - skipping graph creation" 1>&2
        continue
    }

    dirPlots="plots"
    [ -d "$dirPlots" ] || mkdir -p "$dirPlots"

    plot_z_vs_q "$setup"

done


#------------------------------------------------------------------------------
