#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

unset MGRIDGEN_ARCH_PATH
if settings=$($WM_PROJECT_DIR/bin/foamEtcFile config.sh/mgridgen)
then
    . $settings
fi

if [ -e "$MGRIDGEN_ARCH_PATH/include/mgridgen.h" ]
then
    wmake $targetType MGridGenGamgAgglomeration
fi

wmake $targetType pairPatchAgglomeration

#------------------------------------------------------------------------------
