#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh

runApplication decomposePar

echo "Updating fvSchemes to use Gauss"
sed "s/GAUSS/Gauss/g" system/fvSchemes.template > system/fvSchemes

runParallel -s Gauss $(getApplication)


echo "Updating fvSchemes to use fusedGauss"
sed "s/GAUSS/fusedGauss/g" system/fvSchemes.template > system/fvSchemes

runParallel -s fusedGauss $(getApplication)


echo "Updating fvSolution to cache gradients"
sed 's/GRADIENT/"grad(.*)"/g' system/fvSolution.template > system/fvSolution

runParallel -s fusedGaussCached $(getApplication)

# Restore
cp system/fvSolution.template system/fvSolution

#------------------------------------------------------------------------------
