#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase
rm -f topOIsoSurface*.{stl,fms}
foamDictionary system/meshDict -entry surfaceFile -set fileName > /dev/null 

#------------------------------------------------------------------------------
