#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. "${WM_PROJECT_DIR:?}"/bin/tools/LogFunctions  # Tutorial log-file functions
#------------------------------------------------------------------------------

echo "--------"

removeLogs

echo "Cleaning tutorials ..."
foamCleanTutorials -self    # Run recursively but avoid self

echo "--------"

#------------------------------------------------------------------------------
