#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

runApplication decomposePar

SOLVER=PCG runParallel -s PCG $(getApplication) # -debug-switch SolverPerformance=2

SOLVER=GMRES runParallel -s GMRES $(getApplication) # -debug-switch SolverPerformance=2

#------------------------------------------------------------------------------
