#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

unset fileHandler
fileHandler="-fileHandler collated"

restore0Dir

runApplication blockMesh

decompDict="-decomposeParDict system/decomposeParDict.4"

if false
then
    # Simple preparation

    runApplication makeFaMesh

    runApplication decomposePar $fileHandler

else

    # Additional steps (to exercise some functionality)

    runParallel $decompDict -s decompose redistributePar -decompose \
        -no-finite-area $fileHandler

    runParallel $decompDict makeFaMesh $fileHandler

    runParallel -s redistribute redistributePar -overwrite $fileHandler
fi

runParallel $(getApplication) $fileHandler

#------------------------------------------------------------------------------
